### ISSUE TITLE
How to implement Client reconnect?

### ISSUE THREAD

**Issue by endymonium** [syncio/syncio-nodejs#10]
Hi,

my client (browser) does not reconnect when I restart the server. Neither using the default ws (kind of expected) nor when using Socket.IO (not expected) ... is that normal behaviour?

Thanks,
Jan

**Comment by Josema** [comment]
Hi there.

If you restart the server (I guess you mean killing and starting again) you lose all the information that makes the sync of the objects, unless you save all the data in a DB, but I haven't tried that. I would say is normal behavior in any architecture that has server and client.

What would be the expected behavior with Socket.IO in your opinion?

**Comment by endymonium** [comment]
Yes, it's a node server which is restarted (by https://github.com/remy/nodemon), but such a thing might also happen in production in my case.

I'm using dop to synchronize a node backend with a Vue frontend in a browser. Example: in the frontend, I set a configuration value, which is synced via RPC to the server, which saves it into a yaml file. Now the server restarts, connection is lost and not restored anymore. I need to reload the browser page to be able to trigger anything again.

Therefore Socket.IO-client should just reconnect to the server again as soon as it is up.

**Comment by Josema** [comment]
Have you tried reconnecting the node?

https://distributedobjectprotocol.org/api/javascript/Node-reconnect

**Comment by endymonium** [comment]
Well no ... I tried it now and it solves my issue :) Thanks didn't see that option before.

Closing myself ...
