### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by DaneTheory** [syncio/syncio-nodejs#8]
Hey guys! Love this lib and would like to help make some additions. Not finding any contributing guidelines. Is this project open to new people joining to help?

**Comment by Josema** [comment]
Hey there! I'm glad that you like it. At this moment is only me making this library, that's why there are no contributing guidelines yet. If you want to help, is the moment for me to start some documentation for devs.

What do you have in mind to add to the library? What are you missing that would be great to add?

**Comment by Josema** [comment]
Send me an email if you want enzo at josema.es
Closing this.
