### ISSUE TITLE
Roadmap.

### ISSUE THREAD

**Issue by TokenChingy** [syncio/syncio-nodejs#9]
Just wanted to say that this is an excellent little library, I will be implementing this into my personal projects as well as projects for work. Quick question, what's the roadmap like on this? Will there be inter-language support?

**Comment by Josema** [comment]
I'm very glad that you like it :)
The roadmap is more or less this https://github.com/DistributedObjectProtocol/dop/projects/1. But not sure if I'm gonna implement all of it. I'm gonna release the version 1.0.0 soon with some break changes.
Instead of `.observe`, will be `.observeProperty`, `.observeObject` and `.observeAll`
A part from that not too much changes.
What do you mean with inter-language support?

**Comment by TokenChingy** [comment]
If we were to implement this on say C#, will this be possible? Looking at the specification, it seems quite straightforward.

**Comment by Josema** [comment]
Yes, of course. The protocol is just JSON and is easy to implement. Probably the API would be different in C#, but implement the basic features would be easy I think. I don't know C# but if you want to implement it I would work closely with you.
Send me an email if you want enzo at josema.es

**Comment by TokenChingy** [comment]
Will do, when will the 1.0.0 spec be ready? I'd rather not implement now for it to change. And the spec seems unfinished?

**Comment by Josema** [comment]
The 1.0.0 version only affects to the Observer API, doesn't affect the protocol itself. I just wanted to release the 1.0.0 because it's been enough time of testing.
My plan is to release it this month.

**Comment by Josema** [comment]
Hi Jason, finally I changed the API but I didn't publish as 1.0.0 instead I've published under 0.40.0. I want to test everything a bit more before I publish as 1.0.0.

Let me know if you have more questions. Closing this.
